import { Product, Category, PromoBanner } from './types';

export const CATEGORIES: Category[] = [
  { id: 'phones', name: 'Phones & Tablets', icon: 'Smartphone', imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=500&q=80' },
  { id: 'electronics', name: 'Electronics', icon: 'Tv', imageUrl: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=500&q=80' },
  { id: 'fashion', name: 'Fashion', icon: 'Shirt', imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=500&q=80' },
  { id: 'home', name: 'Home & Office', icon: 'Home', imageUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=500&q=80' },
  { id: 'beauty', name: 'Health & Beauty', icon: 'Sparkles', imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=500&q=80' },
  { id: 'supermarket', name: 'Supermarket', icon: 'ShoppingBag', imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=500&q=80' },
  { id: 'farmers-market', name: 'Farmers Market', icon: 'Leaf', imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=500&q=80' },
  { id: 'children', name: 'Children Department', icon: 'Baby', imageUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eb2?auto=format&fit=crop&w=500&q=80' },
  { id: 'men-women', name: 'Men & Women Fashion', icon: 'Users', imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=500&q=80' },
];

export const PROMO_BANNERS: PromoBanner[] = [
  {
    id: 'banner1',
    title: 'Super Shopping Festival',
    subtitle: 'Up to 50% OFF on Smartphones, TVs, and Daily Essentials',
    ctaText: 'Shop Deals Now',
    imageUrl: 'https://picsum.photos/seed/marketbanner1/800/400',
    bgColor: 'from-orange-600 to-red-600',
    accentColor: 'bg-yellow-400 text-slate-900',
  },
  {
    id: 'banner2',
    title: 'Mobile Money Flash Sales',
    subtitle: 'Extra 10% discount when you pay with MTN MoMo or Airtel Money!',
    ctaText: 'Explore MoMo Deals',
    imageUrl: 'https://picsum.photos/seed/momo/800/400',
    bgColor: 'from-yellow-500 to-amber-600',
    accentColor: 'bg-red-600 text-white',
  },
  {
    id: 'banner3',
    title: 'Mukwano & Jesa Store Launch',
    subtitle: 'Save big on local Ugandan home products & fresh dairy hampers.',
    ctaText: 'Support Local Brands',
    imageUrl: 'https://picsum.photos/seed/ugandaprod/800/400',
    bgColor: 'from-emerald-600 to-teal-800',
    accentColor: 'bg-orange-500 text-white',
  }
];

export const PRODUCTS: Product[] = [
  // Phones & Tablets
  {
    id: 'p1',
    title: 'Tecno Spark 20 Pro - High Speed Dual SIM Smartphone',
    price: 685000,
    originalPrice: 850000,
    category: 'phones',
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=400&q=80',
    rating: 4.6,
    reviewsCount: 142,
    discountBadge: '-19%',
    brand: 'Tecno',
    isFlashSale: true,
    isOfficial: true,
    freeDelivery: true,
    payOnDelivery: true,
    inStock: true,
    variations: [
      { name: 'Storage Capacity', options: ['128GB ROM + 6GB RAM', '256GB ROM + 8GB RAM'], priceModifiers: { '128GB ROM + 6GB RAM': -110000, '256GB ROM + 8GB RAM': 0 } },
      { name: 'Color Style', options: ['Lunar Frost', 'Mystery White', 'Horizon Gold'] }
    ],
    vendors: [
      { id: 'v1_1', name: 'Tecno Official Outlet Kampala', price: 685000, rating: 4.9, reviewsCount: 940, deliveryTime: '2-5 Hours (Express Boda)', shippingFee: 0, isOfficial: true, location: 'Kampala Central' },
      { id: 'v1_2', name: 'Ssebaggala Mobiles Ltd', price: 675000, rating: 4.4, reviewsCount: 110, deliveryTime: '1 Day (Standard Courier)', shippingFee: 3500, isOfficial: false, location: 'Wandegeya' },
      { id: 'v1_3', name: 'Alibaba Global Express Direct', price: 615000, rating: 4.1, reviewsCount: 38, deliveryTime: '7-12 Days (Shipped via Cargo)', shippingFee: 45000, isOfficial: false, location: 'Guangzhou, China' }
    ],
    reviews: [
      { name: 'Okello Moses', location: 'Gulu City', rating: 5, text: 'Arrived in Gulu within 24 hours via Horizon Bus! Super fast service and genuine Tecno device.', date: 'June 28, 2026', likes: 12 },
      { name: 'Nakato Sarah', location: 'Kampala', rating: 5, text: 'Excellent battery life, dual SIM is so useful for MTN and Airtel networks. Paid on delivery.', date: 'June 18, 2026', likes: 8 }
    ]
  },
  {
    id: 'p2',
    title: 'Infinix Hot 40i - 128GB ROM - 4GB RAM - Horizon Gold',
    price: 495000,
    originalPrice: 590000,
    category: 'phones',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=400&q=80',
    rating: 4.4,
    reviewsCount: 89,
    discountBadge: '-16%',
    brand: 'Infinix',
    isFlashSale: false,
    isOfficial: true,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
    variations: [
      { name: 'Color', options: ['Horizon Gold', 'Stardust Black'] }
    ],
    vendors: [
      { id: 'v2_1', name: 'Infinix Kampala HQ', price: 495000, rating: 4.8, reviewsCount: 310, deliveryTime: 'Same-day Delivery', shippingFee: 4000, isOfficial: true, location: 'Kampala Plaza' },
      { id: 'v2_2', name: 'Mukono Smart Electronics', price: 490000, rating: 4.2, reviewsCount: 15, deliveryTime: '1 Day (Standard Courier)', shippingFee: 5000, isOfficial: false, location: 'Mukono Town' }
    ],
    reviews: [
      { name: 'Atwine Raymond', location: 'Mbarara', rating: 4, text: 'Perfect budget phone! The gold color looks extremely premium and the screen is super smooth.', date: 'May 12, 2026', likes: 3 }
    ]
  },
  {
    id: 'p3',
    title: 'Samsung Galaxy A15 - Super AMOLED Display',
    price: 749000,
    originalPrice: 899000,
    category: 'phones',
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    reviewsCount: 205,
    discountBadge: '-17%',
    brand: 'Samsung',
    isFlashSale: true,
    isOfficial: true,
    freeDelivery: true,
    payOnDelivery: true,
    inStock: true,
    variations: [
      { name: 'Storage capacity', options: ['128GB ROM + 6GB RAM', '256GB ROM + 8GB RAM'], priceModifiers: { '128GB ROM + 6GB RAM': 0, '256GB ROM + 8GB RAM': 150000 } },
      { name: 'Color', options: ['Blue Black', 'Light Blue', 'Yellow'] }
    ],
    vendors: [
      { id: 'v3_1', name: 'Samsung Experience Store Kampala', price: 749000, rating: 5.0, reviewsCount: 1520, deliveryTime: '2-4 Hours (Boda Express)', shippingFee: 0, isOfficial: true, location: 'Acacia Mall' },
      { id: 'v3_2', name: 'Kiyembe Wholesale Electronics', price: 729000, rating: 4.3, reviewsCount: 203, deliveryTime: '1 Day', shippingFee: 3000, isOfficial: false, location: 'Kiyembe, Kampala' },
      { id: 'v3_3', name: 'Global Direct Import Partner', price: 680000, rating: 4.6, reviewsCount: 4200, deliveryTime: '8-14 Days (Import Duties Paid)', shippingFee: 85000, isOfficial: false, location: 'Seattle, USA' }
    ],
    reviews: [
      { name: 'Namubiru Joy', location: 'Entebbe', rating: 5, text: 'The Super AMOLED screen is incredibly bright and colorful. Best purchase of 2026!', date: 'June 25, 2026', likes: 19 },
      { name: 'Kato Derrick', location: 'Kabale', rating: 4, text: 'Great phone, camera is surprisingly clear in daylight. Delivery to Kabale was smooth.', date: 'June 02, 2026', likes: 11 }
    ]
  },
  {
    id: 'p4',
    title: 'Apple iPhone 15 Pro Max - 256GB - Natural Titanium',
    price: 5200000,
    originalPrice: 5800000,
    category: 'phones',
    image: 'https://picsum.photos/seed/iphone15/400/400',
    rating: 4.9,
    reviewsCount: 64,
    discountBadge: '-10%',
    brand: 'Apple',
    isFlashSale: false,
    isOfficial: false,
    freeDelivery: true,
    payOnDelivery: true,
    inStock: true,
  },

  // Electronics
  {
    id: 'p5',
    title: 'Hisense 43" Smart Frameless Full HD TV - Built-in Receiver & WiFi',
    price: 1150000,
    originalPrice: 1450000,
    category: 'electronics',
    image: 'https://picsum.photos/seed/hisensetv/400/400',
    rating: 4.5,
    reviewsCount: 78,
    discountBadge: '-21%',
    brand: 'Hisense',
    isFlashSale: true,
    isOfficial: true,
    freeDelivery: true,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p6',
    title: 'LG NanoCell 55" 4K Ultra HD Smart TV - Active HDR',
    price: 2450000,
    originalPrice: 2900000,
    category: 'electronics',
    image: 'https://picsum.photos/seed/lgtv/400/400',
    rating: 4.7,
    reviewsCount: 31,
    discountBadge: '-15%',
    brand: 'LG',
    isFlashSale: false,
    isOfficial: true,
    freeDelivery: true,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p7',
    title: 'Sony MHC-V13 High-Power Audio System with Bluetooth & Jet Bass',
    price: 950000,
    originalPrice: 1100000,
    category: 'electronics',
    image: 'https://picsum.photos/seed/sonyspeaker/400/400',
    rating: 4.6,
    reviewsCount: 42,
    discountBadge: '-13%',
    brand: 'Sony',
    isFlashSale: false,
    isOfficial: false,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },

  // Fashion
  {
    id: 'p8',
    title: 'Premium Men Cargo Pants - Slim Fit - Khaki/Beige',
    price: 45000,
    originalPrice: 80000,
    category: 'fashion',
    image: 'https://picsum.photos/seed/cargopants/400/400',
    rating: 4.2,
    reviewsCount: 156,
    discountBadge: '-43%',
    brand: 'Generic',
    isFlashSale: true,
    isOfficial: false,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p9',
    title: 'Unisex Kampala Print African Wax Cotton Short-Sleeve Shirt',
    price: 35000,
    originalPrice: 60000,
    category: 'fashion',
    image: 'https://picsum.photos/seed/africanprint/400/400',
    rating: 4.8,
    reviewsCount: 92,
    discountBadge: '-41%',
    brand: 'Kampala Tailors',
    isFlashSale: true,
    isOfficial: false,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p10',
    title: 'Breathable Sports Sneakers - Lightweight Running Shoes',
    price: 65000,
    originalPrice: 120000,
    category: 'fashion',
    image: 'https://picsum.photos/seed/sportshoes/400/400',
    rating: 4.3,
    reviewsCount: 118,
    discountBadge: '-45%',
    brand: 'Adis',
    isFlashSale: false,
    isOfficial: false,
    freeDelivery: true,
    payOnDelivery: true,
    inStock: true,
  },

  // Home & Office
  {
    id: 'p11',
    title: 'Nice House of Plastics 4-Tier Drawer Cabinet - Multicolor',
    price: 85000,
    originalPrice: 110000,
    category: 'home',
    image: 'https://picsum.photos/seed/nicehouse/400/400',
    rating: 4.7,
    reviewsCount: 220,
    discountBadge: '-22%',
    brand: 'Nice House of Plastics',
    isFlashSale: false,
    isOfficial: true,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p12',
    title: 'Electric Double Hot Plate Stove - 2000W - Durable Stainless Steel',
    price: 75000,
    originalPrice: 120000,
    category: 'home',
    image: 'https://picsum.photos/seed/hotplate/400/400',
    rating: 4.4,
    reviewsCount: 67,
    discountBadge: '-37%',
    brand: 'Sayona',
    isFlashSale: true,
    isOfficial: false,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p13',
    title: 'Non-Stick Aluminum Cooking Pot Casserole Set - 3 Pieces',
    price: 135000,
    originalPrice: 195000,
    category: 'home',
    image: 'https://picsum.photos/seed/potsset/400/400',
    rating: 4.5,
    reviewsCount: 84,
    discountBadge: '-30%',
    brand: 'Dessini',
    isFlashSale: false,
    isOfficial: false,
    freeDelivery: true,
    payOnDelivery: true,
    inStock: true,
  },

  // Health & Beauty
  {
    id: 'p14',
    title: 'Nivea Radiant & Beauty Even Glow Body Lotion - 400ml (Pack of 2)',
    price: 38000,
    originalPrice: 48000,
    category: 'beauty',
    image: 'https://picsum.photos/seed/nivealotion/400/400',
    rating: 4.8,
    reviewsCount: 310,
    discountBadge: '-20%',
    brand: 'Nivea',
    isFlashSale: true,
    isOfficial: true,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p15',
    title: 'Movit Herbal Jelly with Aloe Vera & Shea Butter - 300g',
    price: 8500,
    originalPrice: 12000,
    category: 'beauty',
    image: 'https://picsum.photos/seed/movitjelly/400/400',
    rating: 4.7,
    reviewsCount: 156,
    discountBadge: '-29%',
    brand: 'Movit',
    isFlashSale: false,
    isOfficial: true,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },

  // Supermarket
  {
    id: 'p16',
    title: 'Mukwano Fortune Butto Cooking Oil - 3 Litre Jerrycan',
    price: 24500,
    originalPrice: 29000,
    category: 'supermarket',
    image: 'https://picsum.photos/seed/fortunebutto/400/400',
    rating: 4.9,
    reviewsCount: 450,
    discountBadge: '-15%',
    brand: 'Mukwano',
    isFlashSale: true,
    isOfficial: true,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p17',
    title: 'Supreme Premium Quality Long Grain Basmati Rice - 5kg',
    price: 32000,
    originalPrice: 40000,
    category: 'supermarket',
    image: 'https://picsum.photos/seed/basmatirice/400/400',
    rating: 4.6,
    reviewsCount: 184,
    discountBadge: '-20%',
    brand: 'Supreme',
    isFlashSale: false,
    isOfficial: false,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p18',
    title: 'Jesa Fresh Whole Milk - 500ml Pack (Box of 12)',
    price: 28000,
    originalPrice: 34000,
    category: 'supermarket',
    image: 'https://picsum.photos/seed/jesamilk/400/400',
    rating: 4.9,
    reviewsCount: 125,
    discountBadge: '-17%',
    brand: 'Jesa',
    isFlashSale: false,
    isOfficial: true,
    freeDelivery: true,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p19',
    title: 'Xiaomi Redmi Note 13 - 256GB ROM - 8GB RAM - Dual SIM - Midnight Black',
    price: 845000,
    originalPrice: 980000,
    category: 'phones',
    image: 'https://picsum.photos/seed/redminote/400/400',
    rating: 4.7,
    reviewsCount: 154,
    discountBadge: '-13%',
    brand: 'Xiaomi',
    isFlashSale: true,
    isOfficial: false,
    freeDelivery: true,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p20',
    title: 'Tecno Pop 8 - 64GB ROM - 3GB RAM - Mystery White',
    price: 320000,
    originalPrice: 380000,
    category: 'phones',
    image: 'https://picsum.photos/seed/tecnopop/400/400',
    rating: 4.5,
    reviewsCount: 73,
    discountBadge: '-15%',
    brand: 'Tecno',
    isFlashSale: false,
    isOfficial: true,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p21',
    title: 'Sayona Subwoofer 3.1 Channel - 15000W PMPO - USB/SD/Bluetooth/FM',
    price: 240000,
    originalPrice: 320000,
    category: 'electronics',
    image: 'https://picsum.photos/seed/sayonasub/400/400',
    rating: 4.8,
    reviewsCount: 198,
    discountBadge: '-25%',
    brand: 'Sayona',
    isFlashSale: true,
    isOfficial: true,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p22',
    title: 'Hisense Microwave Oven with Grill - 20L - Black',
    price: 380000,
    originalPrice: 450000,
    category: 'electronics',
    image: 'https://picsum.photos/seed/hisensemicro/400/400',
    rating: 4.6,
    reviewsCount: 61,
    discountBadge: '-15%',
    brand: 'Hisense',
    isFlashSale: false,
    isOfficial: true,
    freeDelivery: true,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p23',
    title: 'Uganda Cranes Official Home Fan Jersey - Yellow & Black',
    price: 40000,
    originalPrice: 60000,
    category: 'fashion',
    image: 'https://picsum.photos/seed/cranesjersey/400/400',
    rating: 4.9,
    reviewsCount: 324,
    discountBadge: '-33%',
    brand: 'Uganda Cranes',
    isFlashSale: true,
    isOfficial: false,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p24',
    title: 'Premium Men Genuine Leather Chelsea Boots - Tan Brown',
    price: 120000,
    originalPrice: 180000,
    category: 'fashion',
    image: 'https://picsum.photos/seed/chelseaboot/400/400',
    rating: 4.7,
    reviewsCount: 104,
    discountBadge: '-33%',
    brand: 'LeatherCraft',
    isFlashSale: false,
    isOfficial: false,
    freeDelivery: true,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p25',
    title: 'Sayona Stainless Steel Electric Cordless Kettle - 1.8 Litres',
    price: 35000,
    originalPrice: 50000,
    category: 'home',
    image: 'https://picsum.photos/seed/sayonakettle/400/400',
    rating: 4.5,
    reviewsCount: 137,
    discountBadge: '-30%',
    brand: 'Sayona',
    isFlashSale: true,
    isOfficial: true,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p26',
    title: 'Eurosonic Multi-Functional Kitchen Blender with Dry Grinder - 1.5L',
    price: 95000,
    originalPrice: 130000,
    category: 'home',
    image: 'https://picsum.photos/seed/blender/400/400',
    rating: 4.6,
    reviewsCount: 88,
    discountBadge: '-26%',
    brand: 'Sayona',
    isFlashSale: false,
    isOfficial: false,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p27',
    title: 'Vaseline Intensive Care Cocoa Radiant Body Lotion - 400ml',
    price: 22000,
    originalPrice: 28000,
    category: 'beauty',
    image: 'https://picsum.photos/seed/vaselinecocoa/400/400',
    rating: 4.8,
    reviewsCount: 243,
    discountBadge: '-21%',
    brand: 'Nivea',
    isFlashSale: true,
    isOfficial: false,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p28',
    title: 'CeraVe Hydrating Facial Cleanser for Normal to Dry Skin - 236ml',
    price: 65000,
    originalPrice: 80000,
    category: 'beauty',
    image: 'https://picsum.photos/seed/ceravecleanse/400/400',
    rating: 4.7,
    reviewsCount: 112,
    discountBadge: '-18%',
    brand: 'Movit',
    isFlashSale: false,
    isOfficial: false,
    freeDelivery: true,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p29',
    title: 'Mukwano Laundry Bar Soap - White (Box of 10 Bars)',
    price: 22500,
    originalPrice: 27000,
    category: 'supermarket',
    image: 'https://picsum.photos/seed/soap/400/400',
    rating: 4.9,
    reviewsCount: 512,
    discountBadge: '-16%',
    brand: 'Mukwano',
    isFlashSale: true,
    isOfficial: true,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p30',
    title: 'Jesa Premium Vanilla Thick Yogurt - 500ml Cup (Pack of 6)',
    price: 18000,
    originalPrice: 22000,
    category: 'supermarket',
    image: 'https://picsum.photos/seed/jesayogurt/400/400',
    rating: 4.9,
    reviewsCount: 167,
    discountBadge: '-18%',
    brand: 'Jesa',
    isFlashSale: false,
    isOfficial: true,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p31',
    title: 'Fresh Organic Matooke Bundle (Direct from Mbarara Farms)',
    price: 35000,
    originalPrice: 45000,
    category: 'farmers-market',
    image: 'https://images.unsplash.com/photo-1566393028639-d108a42c46a7?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    reviewsCount: 320,
    discountBadge: '-22%',
    brand: 'Mbarara Fresh',
    isFlashSale: true,
    isOfficial: true,
    freeDelivery: true,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p32',
    title: 'Premium Jesa Farm Fresh Milk Box - 1L (Pack of 12)',
    price: 32000,
    originalPrice: 38000,
    category: 'farmers-market',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    reviewsCount: 189,
    discountBadge: '-15%',
    brand: 'Jesa',
    isFlashSale: false,
    isOfficial: true,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p33',
    title: 'Kids Educational interactive Music Toy Tablet with Lights',
    price: 85000,
    originalPrice: 110000,
    category: 'children',
    image: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    reviewsCount: 94,
    discountBadge: '-22%',
    brand: 'Toys Hub',
    isFlashSale: false,
    isOfficial: false,
    freeDelivery: true,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p34',
    title: 'Soft Cotton Children Sleeping Pajamas Set - Cute Animals',
    price: 45000,
    originalPrice: 60000,
    category: 'children',
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77eb2?auto=format&fit=crop&w=400&q=80',
    rating: 4.6,
    reviewsCount: 45,
    discountBadge: '-25%',
    brand: 'BabyCare',
    isFlashSale: true,
    isOfficial: false,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p35',
    title: 'Genuine Leather Men\'s Classic Chelsea Boots - Dark Brown',
    price: 120000,
    originalPrice: 180000,
    category: 'men-women',
    image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    reviewsCount: 210,
    discountBadge: '-33%',
    brand: 'Kampala Leather',
    isFlashSale: true,
    isOfficial: true,
    freeDelivery: true,
    payOnDelivery: true,
    inStock: true,
  },
  {
    id: 'p36',
    title: 'Elegant Flowy Chiffon Women\'s Maxi Dress - Floral Print',
    price: 85000,
    originalPrice: 120000,
    category: 'men-women',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    reviewsCount: 78,
    discountBadge: '-29%',
    brand: 'Glamour UG',
    isFlashSale: false,
    isOfficial: false,
    freeDelivery: false,
    payOnDelivery: true,
    inStock: true,
  }
];

export const UGANDA_DISTRICTS = [
  'Kampala (Central)',
  'Kampala (Nakawa)',
  'Kampala (Makindye)',
  'Kampala (Rubaga)',
  'Kampala (Kawempe)',
  'Entebbe',
  'Wakiso',
  'Mukono',
  'Jinja',
  'Mbarara',
  'Gulu',
  'Arua',
  'Mbale',
  'Masaka',
  'Fort Portal',
  'Lira',
  'Kabale'
];

export const POPULAR_BRANDS = [
  'Tecno',
  'Infinix',
  'Samsung',
  'Apple',
  'Hisense',
  'LG',
  'Mukwano',
  'Nice House of Plastics',
  'Nivea',
  'Movit',
  'Jesa'
];
